version: '3.8'

services:
  postgres:
    image: postgres:14.1
    networks:
      local:
        aliases:
          - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boosters
    ports:
      - 5432:5432

  migrate:
    image: migrate/migrate
    networks:
      - local
    volumes:
      - ../../migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@database:5432/boosters?sslmode=disable", "up", "2"]
    links:
      - postgres
    restart: on-failure

  service:
    container_name: service
    networks:
      - local
    ports:
      - 8000:8000
    build:
      context: ../../
      dockerfile: ./deploy/local/Dockerfile
    restart: on-failure
    command: ./deploy/local/wait-for-it.sh postgres:5432 -t 60 -- ./main

networks:
  local: